export const SLUG_TO_NAMESPACE: Record<string, string> = {
  "pdf-merge": "PdfMerger",
  "compress-pdf": "PdfCompressor",
  "json-formatter": "JsonFormatter",
  "compress-image": "ImageCompressor",
  "image-convert": "ImageConverter",
  "split-pdf": "PdfSplitter",
  "base64-encode-decode": "Base64",
  "image-to-pdf": "ImageToPdf",
  "pdf-rotate": "PdfRotator",
  "image-resize": "ImageResizer",
  "image-crop": "ImageCrop",
  "url-encode-decode": "UrlEncoder",
  "jwt-decoder": "JwtDecoder",
  "uuid-generator": "UuidGenerator",
  "hash-generator": "HashGenerator",
  "video-to-gif": "VideoToGif",
  "extract-frames": "ExtractFrames",
  "video-thumbnail": "VideoThumbnail",
  "video-metadata": "VideoMetadata",
  "zip-files": "ZipFiles",
  "unzip-files": "UnzipFiles",
  "word-counter": "WordCounter",
  "case-converter": "CaseConverter",
  "lorem-ipsum-generator": "LoremIpsum",
  "duplicate-line-remover": "DuplicateLineRemover",
  "line-sorter": "LineSorter",
};
